# Generated by Django 5.2.10 on 2026-03-31 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_taikhoan_username_taikhoan_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='tai_khoan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_vien', to='store.taikhoan'),
        ),
    ]
