# Generated by Django 5.2.10 on 2026-03-31 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_khachhang_tai_khoan_alter_khachhang_dien_thoai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPhamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.sanpham')),
            ],
            options={
                'db_table': 'san_pham_image',
            },
        ),
    ]
