# Generated by Django 5.2.10 on 2026-04-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_sanphamimage_thu_tu_danhgiasanpham'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinhLuanSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('so_sao', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hien_thi', models.BooleanField(default=True)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luans', to='store.sanpham')),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan_san_phams', to='store.taikhoan')),
            ],
            options={
                'db_table': 'binh_luan_san_pham',
                'ordering': ['-created_at'],
            },
        ),
    ]
