# Generated by Django 5.2.10 on 2026-04-04 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_chinhanh_latitude_alter_chinhanh_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinhanh',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.CreateModel(
            name='BinhLuanChiNhanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.IntegerField(default=5)),
                ('noi_dung', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luans', to='store.chinhanh')),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.taikhoan')),
            ],
            options={
                'unique_together': {('chi_nhanh', 'tai_khoan')},
            },
        ),
    ]
