# Generated by Django 5.2.10 on 2026-04-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_chinhanh_hinh_anh'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonKhoChiNhanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_ton', models.IntegerField(default=0)),
                ('muc_can_canh_bao', models.IntegerField(default=5)),
                ('is_hien_thi', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_khos', to='store.chinhanh')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_khos', to='store.sanpham')),
            ],
            options={
                'db_table': 'ton_kho_chi_nhanh',
                'ordering': ['chi_nhanh__ten_chi_nhanh', 'san_pham__ten_san_pham'],
                'unique_together': {('chi_nhanh', 'san_pham')},
            },
        ),
    ]
