# Generated by Django 5.2.10 on 2026-04-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_tonkhochinhanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='bao_quan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='cach_su_dung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='cong_dung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='han_su_dung',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='luu_y',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='quy_cach_dong_goi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='thanh_phan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='xuat_xu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
