# Generated by Django 5.2.10 on 2026-03-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiNhanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chi_nhanh', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dien_thoai', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'chi_nhanh',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(max_length=100)),
                ('dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'khach_hang',
            },
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'loai_san_pham',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ncc', models.CharField(max_length=150)),
                ('dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'nha_cung_cap',
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('ho_ten', models.CharField(blank=True, max_length=100, null=True)),
                ('dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('USER', 'User'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='USER', max_length=10)),
                ('trang_thai', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tai_khoan',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhan_vien', models.CharField(max_length=100)),
                ('chuc_vu', models.CharField(max_length=50)),
                ('luong', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_viens', to='store.chinhanh')),
                ('tai_khoan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_viens', to='store.taikhoan')),
            ],
            options={
                'db_table': 'nhan_vien',
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lap', models.DateTimeField()),
                ('dia_chi_giao_hang', models.CharField(blank=True, max_length=200, null=True)),
                ('sdt_nguoi_nhan', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_nguoi_nhan', models.CharField(blank=True, max_length=100, null=True)),
                ('trang_thai', models.CharField(choices=[('CHO_XU_LY', 'Chờ xử lý'), ('DA_XAC_NHAN', 'Đã xác nhận'), ('DANG_GIAO', 'Đang giao'), ('HOAN_TAT', 'Hoàn tất'), ('HUY', 'Hủy')], default='CHO_XU_LY', max_length=30)),
                ('phuong_thuc_thanh_toan', models.CharField(blank=True, max_length=30, null=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_dons', to='store.khachhang')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_dons', to='store.nhanvien')),
            ],
            options={
                'db_table': 'hoa_don',
            },
        ),
        migrations.CreateModel(
            name='NhapHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateTimeField()),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhap_hangs', to='store.nhacungcap')),
            ],
            options={
                'db_table': 'nhap_hang',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=150)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('so_luong', models.IntegerField()),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh_anh_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_khuyen_mai', models.BooleanField(default=False)),
                ('gia_khuyen_mai', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gia_goc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_phams', to='store.loaisanpham')),
            ],
            options={
                'db_table': 'san_pham',
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhapHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_gia_nhap', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nhap_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='store.nhaphang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_nhap_hangs', to='store.sanpham')),
            ],
            options={
                'db_table': 'chi_tiet_nhap_hang',
                'unique_together': {('nhap_hang', 'san_pham')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='store.hoadon')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_hoa_dons', to='store.sanpham')),
            ],
            options={
                'db_table': 'chi_tiet_hoa_don',
                'unique_together': {('hoa_don', 'san_pham')},
            },
        ),
    ]
