# Generated by Django 5.2.10 on 2026-03-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taikhoan',
            name='username',
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='ho_ten',
            field=models.CharField(default='Chưa cập nhật', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to='store.taikhoan')),
            ],
            options={
                'db_table': 'email_otp',
                'ordering': ['-created_at'],
            },
        ),
    ]
