# Generated by Django 5.2.10 on 2026-03-31 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_nhanvien_tai_khoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='tai_khoan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khach_hang', to='store.taikhoan'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='chi_nhanh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_viens', to='store.chinhanh'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='chuc_vu',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='luong',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
