# Generated by Django 5.2.10 on 2026-04-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sanphamimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanphamimage',
            options={'ordering': ['thu_tu', 'id']},
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='hinh_anh_url',
        ),
        migrations.RemoveField(
            model_name='sanphamimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='sanphamimage',
            name='image',
            field=models.ImageField(default='san_pham/default.jpg', upload_to='san_pham/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanphamimage',
            name='la_anh_chinh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanphamimage',
            name='thu_tu',
            field=models.PositiveSmallIntegerField(default=0, help_text='Thứ tự hiển thị (0 = đầu tiên)'),
        ),
    ]
