# Generated by Django 5.2.10 on 2026-04-01 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_sanphamimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanphamimage',
            name='thu_tu',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DanhGiaSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nguoi_dung', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('so_sao', models.PositiveSmallIntegerField(default=5)),
                ('noi_dung', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hien_thi', models.BooleanField(default=True)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gias', to='store.sanpham')),
            ],
            options={
                'db_table': 'danh_gia_san_pham',
                'ordering': ['-created_at'],
            },
        ),
    ]
