# Generated by Django 5.2.10 on 2026-04-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_binhluansanpham'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='binhluansanpham',
            constraint=models.UniqueConstraint(fields=('san_pham', 'tai_khoan'), name='unique_binh_luan_per_user_per_product'),
        ),
    ]
