# Generated by Django 5.2.10 on 2026-04-04 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_binhluansanpham_unique_binh_luan_per_user_per_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinhanh',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vĩ độ (Chỉ nhận giá trị tại VN: 8.0 đến 24.0)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(8.0), django.core.validators.MaxValueValidator(24.0)]),
        ),
        migrations.AlterField(
            model_name='chinhanh',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Kinh độ (Chỉ nhận giá trị tại VN: 102.0 đến 110.0)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(102.0), django.core.validators.MaxValueValidator(110.0)]),
        ),
    ]
