# Generated by Django 5.2.10 on 2026-04-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_chinhanh_hinh_anh_binhluanchinhanh'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinhLuanChiNhanhImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment_images/%Y/%m/')),
                ('binh_luan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.binhluanchinhanh')),
            ],
        ),
        migrations.CreateModel(
            name='ChiNhanhImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_gallery/%Y/%m/')),
                ('chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.chinhanh')),
            ],
            options={
                'db_table': 'chi_nhanh_image',
            },
        ),
    ]
