# Generated by Django 5.2.10 on 2026-04-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_binhluanchinhanhimage_chinhanhimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='binhluanchinhanhimage',
            table='binh_luan_chi_nhanh_image',
        ),
    ]
