# Generated by Django 5.2.10 on 2026-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_binhluanchinhanhimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinhanh',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/', verbose_name='Ảnh đại diện chính (Sẽ hiện ở ngoài danh sách)'),
        ),
    ]
