# Generated by Django 5.2.10 on 2026-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cua_hang', models.CharField(max_length=200, verbose_name='Tên cửa hàng')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('so_dien_thoai', models.CharField(max_length=20, verbose_name='Hotline')),
                ('vi_do', models.FloatField(verbose_name='Latitude (Vĩ độ)')),
                ('kinh_do', models.FloatField(verbose_name='Longitude (Kinh độ)')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='store_images/')),
            ],
        ),
    ]
